### ISSUE TITLE
L'exe ne peut pas installer les fichiers car distribué "sans licence"

### ISSUE THREAD

**Issue by Yellow375** [pacatransports/gx337vol3fe#2]
Salut !
J'ai récemment téléchargé la release sortie le 4 avril et l'installateur ne marche pas en affichant ce message 
![image](https://github.com/pacatransports/gx337vol3fe/assets/44520645/178f5ed0-6f9b-4724-b942-ece0ad9eecc2)
Je ne peux rien faire étant donné que le zip est protégé par un mot de passe :/ (alors que ça peut juste s'extraire dans le dossier Vehicles non ?)

**Comment by pacatransports** [comment]
Bug corrigé sur la dernière release 😉

**Comment by Yellow375** [comment]
J'ai téléchargé la dernière release et effectivement, l'installateur démarre mais me dit instantanément que l'installation est finie alors que rien n'a changé. Normal ?

**Comment by pacatransports** [comment]
C'est (re)corrigé! Désolé pour le dérangement. N'hésite pas à partager mon mod 😉

**Comment by Yellow375** [comment]
On avance j'ai des logs !
De mauvais mot de passe donc les fichiers sont vides (et btw l'installateur se fait flag par Windows Defender)

**Comment by Yellow375** [comment]
L'installation a marchée !
Je testerais le mod demain :)
